
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqnatcywnnttjxweomud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxbmF0Y3l3bm50dGp4d2VvbXVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNDk1OTMsImV4cCI6MjA1OTgyNTU5M30.uzj9UgcQLjpbAOXMDF_zN-3sC7ELe3LsArQTMmb8oG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  db: {
    schema: 'public',
  },
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'voilia-auth-session',
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});

// Debug authentication issues
supabase.auth.onAuthStateChange((event, session) => {
  console.log('Auth state changed:', event, session?.user?.email || 'No user');
});
